version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: server 
    restart: always
    command: pnpm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - default

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres:

networks:
  default: